#!/usr/bin/with-contenv bash

#chmod o+rw /var/run/docker.sock
#apt-get update && apt-get install --quiet --yes --no-install-recommends docker.io
echo "**** install latest rclone beta ****" && \
 curl https://rclone.org/install.sh | bash -s beta
 
